name: Sync

on:
  workflow_dispatch:

jobs:
  dotfiles:
    name: 'Sync: dotfiles'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.repository.name }} repository
        uses: actions/checkout@v2
        with:
          path: __main__

      - name: Checkout ${{ github.actor }} repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.actor }}/${{ github.actor }}
          path: ${{ github.actor }}

      - name: Checkout dotfiles repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.actor }}/dotfiles
          path: dotfiles
          fetch-depth: 0

      - name: Sync dotfiles
        shell: pwsh
        run: ./${{ github.actor }}/SyncDotFiles.ps1 __main__

      - name: Create pull request
        env:
          BRANCH: ci/dotfiles-
          TITLE: '[CI] Update dotfiles'
          MESSAGE: Update dotfiles
          LABEL: ci
          BODY: ''
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ matrix.repository }}
          time=$(date +%s)
          branch_name=$BRANCH$time
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions"
          git checkout -b $branch_name
          git add .
          git diff-index --quiet HEAD || (git commit -m "$MESSAGE"; git push --set-upstream origin $branch_name; gh pr create --title "$TITLE" --label "$LABEL" --body "$BODY")